export interface RalColor {
  hex: string;
  ralCode: string;
  group: string; // yellow, orange, red, purple, blue, green, grey, brown, black_white
  nameUk: string;
  nameRu: string;
  nameEn: string;
}

export interface RalGroup {
  key: string;
  nameUk: string;
  nameRu: string;
  nameEn: string;
  colorSample: string;
  icon: string;
}

export const RAL_GROUPS: RalGroup[] = [
  { key: 'yellow', nameUk: 'Жовті', nameRu: 'Желтые', nameEn: 'Yellows', colorSample: '#F3C010', icon: '🟡' },
  { key: 'orange', nameUk: 'Оранжеві', nameRu: 'Оранжевые', nameEn: 'Oranges', colorSample: '#E15501', icon: '🍊' },
  { key: 'red', nameUk: 'Червоні', nameRu: 'Красные', nameEn: 'Reds', colorSample: '#C1121C', icon: '🔴' },
  { key: 'purple', nameUk: 'Фіолетові', nameRu: 'Фиолетовые', nameEn: 'Purples', colorSample: '#922B79', icon: '🟣' },
  { key: 'blue', nameUk: 'Сині', nameRu: 'Синие', nameEn: 'Blues', colorSample: '#00438A', icon: '🔵' },
  { key: 'green', nameUk: 'Зелені', nameRu: 'Зеленые', nameEn: 'Greens', colorSample: '#0E4438', icon: '🟢' },
  { key: 'grey', nameUk: 'Сірі', nameRu: 'Серые', nameEn: 'Greys', colorSample: '#373D43', icon: '⚪' },
  { key: 'brown', nameUk: 'Коричневі', nameRu: 'Коричневые', nameEn: 'Browns', colorSample: '#442F29', icon: '🟤' },
  { key: 'black_white', nameUk: 'Чорні та Білі', nameRu: 'Черные и Белые', nameEn: 'Black & White', colorSample: '#0A0A0A', icon: '🖤' },
];

export const RAL_CLASSIC_COLLECTION: RalColor[] = [
  // 1000 - Жовті
  { hex: '#CDA434', ralCode: 'RAL 1000', group: 'yellow', nameUk: 'Зелено-бежевий', nameRu: 'Зелено-бежевый', nameEn: 'Green beige' },
  { hex: '#D7C49E', ralCode: 'RAL 1001', group: 'yellow', nameUk: 'Бежевий', nameRu: 'Бежевый', nameEn: 'Beige' },
  { hex: '#C6A664', ralCode: 'RAL 1002', group: 'yellow', nameUk: 'Піщано-жовтий', nameRu: 'Песочно-желтый', nameEn: 'Sand yellow' },
  { hex: '#F9A800', ralCode: 'RAL 1003', group: 'yellow', nameUk: 'Сигнальний жовтий', nameRu: 'Сигнальный желтый', nameEn: 'Signal yellow' },
  { hex: '#E49B0F', ralCode: 'RAL 1004', group: 'yellow', nameUk: 'Золотисто-жовтий', nameRu: 'Золотисто-желтый', nameEn: 'Golden yellow' },
  { hex: '#CB8E00', ralCode: 'RAL 1005', group: 'yellow', nameUk: 'Медово-жовтий', nameRu: 'Медово-желтый', nameEn: 'Honey yellow' },
  { hex: '#E29000', ralCode: 'RAL 1006', group: 'yellow', nameUk: 'Кукурудзяно-жовтий', nameRu: 'Кукурузно-желтый', nameEn: 'Maize yellow' },
  { hex: '#F8A300', ralCode: 'RAL 1007', group: 'yellow', nameUk: 'Нарцисово-жовтий', nameRu: 'Нарциссово-желтый', nameEn: 'Daffodil yellow' },
  { hex: '#997A4D', ralCode: 'RAL 1011', group: 'yellow', nameUk: 'Коричнево-бежевий', nameRu: 'Коричнево-бежевый', nameEn: 'Brown beige' },
  { hex: '#CDAE36', ralCode: 'RAL 1012', group: 'yellow', nameUk: 'Лимонно-жовтий', nameRu: 'Лимонно-желтый', nameEn: 'Lemon yellow' },
  { hex: '#E3D9C6', ralCode: 'RAL 1013', group: 'yellow', nameUk: 'Перлиново-білий', nameRu: 'Жемчужно-белый', nameEn: 'Oyster white' },
  { hex: '#DDC8A4', ralCode: 'RAL 1014', group: 'yellow', nameUk: 'Слонова кістка', nameRu: 'Слоновая кость', nameEn: 'Ivory' },
  { hex: '#E6D6B8', ralCode: 'RAL 1015', group: 'yellow', nameUk: 'Світла слонова кістка', nameRu: 'Светлая слоновая кость', nameEn: 'Light ivory' },
  { hex: '#F2E312', ralCode: 'RAL 1016', group: 'yellow', nameUk: 'Сірчано-жовтий', nameRu: 'Серно-желтый', nameEn: 'Sulfur yellow' },
  { hex: '#F5C57A', ralCode: 'RAL 1017', group: 'yellow', nameUk: 'Шафраново-жовтий', nameRu: 'Шафраново-желтый', nameEn: 'Saffron yellow' },
  { hex: '#F3E03B', ralCode: 'RAL 1018', group: 'yellow', nameUk: 'Цинково-жовтий', nameRu: 'Цинково-желтый', nameEn: 'Zinc yellow' },
  { hex: '#A29680', ralCode: 'RAL 1019', group: 'yellow', nameUk: 'Сіро-бежевий', nameRu: 'Серо-бежевый', nameEn: 'Grey beige' },
  { hex: '#9B945A', ralCode: 'RAL 1020', group: 'yellow', nameUk: 'Оливково-жовтий', nameRu: 'Оливково-желтый', nameEn: 'Olive yellow' },
  { hex: '#F3C010', ralCode: 'RAL 1021', group: 'yellow', nameUk: 'Ріпаково-жовтий', nameRu: 'Рапсово-желтый', nameEn: 'Rape Yellow' },
  { hex: '#FAD201', ralCode: 'RAL 1023', group: 'yellow', nameUk: 'Трафіковий жовтий', nameRu: 'Трафиковый желтый', nameEn: 'Traffic yellow' },
  { hex: '#BA8F4C', ralCode: 'RAL 1024', group: 'yellow', nameUk: 'Охра жовта', nameRu: 'Охра желтая', nameEn: 'Ochre yellow' },
  { hex: '#F5FF00', ralCode: 'RAL 1026', group: 'yellow', nameUk: 'Люмінесцентний жовтий', nameRu: 'Люминесцентный желтый', nameEn: 'Luminous yellow' },
  { hex: '#A08F32', ralCode: 'RAL 1027', group: 'yellow', nameUk: 'Каррі', nameRu: 'Карри', nameEn: 'Curry' },
  { hex: '#F8A000', ralCode: 'RAL 1028', group: 'yellow', nameUk: 'Диня жовта', nameRu: 'Дыня желтая', nameEn: 'Melon yellow' },
  { hex: '#DAA520', ralCode: 'RAL 1032', group: 'yellow', nameUk: 'Жовтий верес', nameRu: 'Желтый вереск', nameEn: 'Broom yellow' },
  { hex: '#F3A530', ralCode: 'RAL 1033', group: 'yellow', nameUk: 'Жоржиново-жовтий', nameRu: 'Георгиново-желтый', nameEn: 'Dahlia yellow' },
  { hex: '#EAA257', ralCode: 'RAL 1034', group: 'yellow', nameUk: 'Пастельно-жовтий', nameRu: 'Пастельно-желтый', nameEn: 'Pastel yellow' },

  // 2000 - Оранжеві
  { hex: '#DD7927', ralCode: 'RAL 2000', group: 'orange', nameUk: 'Жовто-оранжевий', nameRu: 'Желто-оранжевый', nameEn: 'Yellow orange' },
  { hex: '#BC4325', ralCode: 'RAL 2001', group: 'orange', nameUk: 'Червоно-оранжевий', nameRu: 'Красно-оранжевый', nameEn: 'Red orange' },
  { hex: '#C63927', ralCode: 'RAL 2002', group: 'orange', nameUk: 'Вермільйон', nameRu: 'Вермильон', nameEn: 'Vermilion' },
  { hex: '#F58134', ralCode: 'RAL 2003', group: 'orange', nameUk: 'Пастельно-оранжевий', nameRu: 'Пастельно-оранжевый', nameEn: 'Pastel orange' },
  { hex: '#E15501', ralCode: 'RAL 2004', group: 'orange', nameUk: 'Чистий оранжевий', nameRu: 'Чистый оранжевый', nameEn: 'Pure orange' },
  { hex: '#FF4F00', ralCode: 'RAL 2005', group: 'orange', nameUk: 'Люмінесцентний оранжевий', nameRu: 'Люминесцентный оранжевый', nameEn: 'Luminous orange' },
  { hex: '#E25303', ralCode: 'RAL 2008', group: 'orange', nameUk: 'Яскраво-червоно-оранжевий', nameRu: 'Ярко-красно-оранжевый', nameEn: 'Bright red orange' },
  { hex: '#D9501E', ralCode: 'RAL 2009', group: 'orange', nameUk: 'Трафіковий оранжевий', nameRu: 'Трафиковый оранжевый', nameEn: 'Traffic orange' },
  { hex: '#D44D22', ralCode: 'RAL 2010', group: 'orange', nameUk: 'Сигнальний оранжевий', nameRu: 'Сигнальный оранжевый', nameEn: 'Signal orange' },
  { hex: '#EC6B22', ralCode: 'RAL 2011', group: 'orange', nameUk: 'Глибоко-оранжевий', nameRu: 'Глубокий оранжевый', nameEn: 'Deep orange' },
  { hex: '#DB6A50', ralCode: 'RAL 2012', group: 'orange', nameUk: 'Лососево-оранжевий', nameRu: 'Лососево-оранжевый', nameEn: 'Salmon orange' },

  // 3000 - Червоні
  { hex: '#AF2B1E', ralCode: 'RAL 3000', group: 'red', nameUk: 'Вогняно-червоний', nameRu: 'Огненно-красный', nameEn: 'Flame red' },
  { hex: '#A52019', ralCode: 'RAL 3001', group: 'red', nameUk: 'Сигнальний червоний', nameRu: 'Сигнальный красный', nameEn: 'Signal red' },
  { hex: '#9B111E', ralCode: 'RAL 3002', group: 'red', nameUk: 'Карміново-червоний', nameRu: 'Карминово-красный', nameEn: 'Carmine red' },
  { hex: '#8B1C22', ralCode: 'RAL 3003', group: 'red', nameUk: 'Рубіново-червоний', nameRu: 'Рубиново-красный', nameEn: 'Ruby red' },
  { hex: '#6B1C23', ralCode: 'RAL 3004', group: 'red', nameUk: 'Пурпурно-червоний', nameRu: 'Пурпурно-красный', nameEn: 'Purple red' },
  { hex: '#5B212B', ralCode: 'RAL 3005', group: 'red', nameUk: 'Винно-червоний', nameRu: 'Винно-красный', nameEn: 'Wine red' },
  { hex: '#2D1B1E', ralCode: 'RAL 3007', group: 'red', nameUk: 'Чорно-червоний', nameRu: 'Черно-красный', nameEn: 'Black red' },
  { hex: '#70332B', ralCode: 'RAL 3009', group: 'red', nameUk: 'Оксидно-червоний', nameRu: 'Оксидно-красный', nameEn: 'Oxide red' },
  { hex: '#782D2A', ralCode: 'RAL 3011', group: 'red', nameUk: 'Коричнево-червоний', nameRu: 'Коричнево-красный', nameEn: 'Brown red' },
  { hex: '#C08A80', ralCode: 'RAL 3012', group: 'red', nameUk: 'Бежево-червоний', nameRu: 'Бежево-красный', nameEn: 'Beige red' },
  { hex: '#9E2B27', ralCode: 'RAL 3013', group: 'red', nameUk: 'Томатно-червоний', nameRu: 'Томатно-красный', nameEn: 'Tomato red' },
  { hex: '#D38388', ralCode: 'RAL 3014', group: 'red', nameUk: 'Антично-рожевий', nameRu: 'Антично-розовый', nameEn: 'Antique pink' },
  { hex: '#E1A6AD', ralCode: 'RAL 3015', group: 'red', nameUk: 'Світло-рожевий', nameRu: 'Светло-розовый', nameEn: 'Light pink' },
  { hex: '#B34446', ralCode: 'RAL 3016', group: 'red', nameUk: 'Коралово-червоний', nameRu: 'Кораллово-красный', nameEn: 'Coral red' },
  { hex: '#CC5B64', ralCode: 'RAL 3017', group: 'red', nameUk: 'Рожевий', nameRu: 'Розовый', nameEn: 'Rose' },
  { hex: '#CD3649', ralCode: 'RAL 3018', group: 'red', nameUk: 'Полунично-червоний', nameRu: 'Клубнично-красный', nameEn: 'Strawberry red' },
  { hex: '#C1121C', ralCode: 'RAL 3020', group: 'red', nameUk: 'Трафіковий червоний', nameRu: 'Трафиковый красный', nameEn: 'Traffic red' },
  { hex: '#D56D65', ralCode: 'RAL 3022', group: 'red', nameUk: 'Лососево-рожевий', nameRu: 'Лососево-розовый', nameEn: 'Salmon pink' },
  { hex: '#FF2A00', ralCode: 'RAL 3024', group: 'red', nameUk: 'Люмінесцентний червоний', nameRu: 'Люминесцентный красный', nameEn: 'Luminous red' },
  { hex: '#A72632', ralCode: 'RAL 3027', group: 'red', nameUk: 'Малиново-червоний', nameRu: 'Малиново-красный', nameEn: 'Raspberry red' },

  // 4000 - Фіолетові
  { hex: '#8B5A75', ralCode: 'RAL 4001', group: 'purple', nameUk: 'Червоно-бузковий', nameRu: 'Красно-сиреневый', nameEn: 'Red lilac' },
  { hex: '#6A3742', ralCode: 'RAL 4002', group: 'purple', nameUk: 'Червоно-фіолетовий', nameRu: 'Красно-фиолетовый', nameEn: 'Red violet' },
  { hex: '#C66497', ralCode: 'RAL 4003', group: 'purple', nameUk: 'Вересово-фіолетовий', nameRu: 'Вересково-фиолетовый', nameEn: 'Heather violet' },
  { hex: '#4C1D36', ralCode: 'RAL 4004', group: 'purple', nameUk: 'Бордово-фіолетовий', nameRu: 'Бордово-фиолетовый', nameEn: 'Claret violet' },
  { hex: '#6C6885', ralCode: 'RAL 4005', group: 'purple', nameUk: 'Синьо-бузковий', nameRu: 'Сине-сиреневый', nameEn: 'Blue lilac' },
  { hex: '#922B79', ralCode: 'RAL 4006', group: 'purple', nameUk: 'Трафіковий пурпур', nameRu: 'Трафиковый пурпур', nameEn: 'Traffic purple' },
  { hex: '#4A2A38', ralCode: 'RAL 4007', group: 'purple', nameUk: 'Пурпурно-фіолетовий', nameRu: 'Пурпурно-фиолетовый', nameEn: 'Purple violet' },
  { hex: '#904684', ralCode: 'RAL 4008', group: 'purple', nameUk: 'Сигнальний фіолетовий', nameRu: 'Сигнальный фиолетовый', nameEn: 'Signal violet' },
  { hex: '#A18B99', ralCode: 'RAL 4009', group: 'purple', nameUk: 'Пастельно-фіолетовий', nameRu: 'Пастельно-фиолетовый', nameEn: 'Pastel violet' },
  { hex: '#CF3476', ralCode: 'RAL 4010', group: 'purple', nameUk: 'Телемаджента', nameRu: 'Телемаджента', nameEn: 'Telemagenta' },

  // 5000 - Сині
  { hex: '#354D73', ralCode: 'RAL 5000', group: 'blue', nameUk: 'Фіолетово-синій', nameRu: 'Фиолетово-синий', nameEn: 'Violet blue' },
  { hex: '#1F344D', ralCode: 'RAL 5001', group: 'blue', nameUk: 'Зелено-синій', nameRu: 'Зелено-синий', nameEn: 'Green blue' },
  { hex: '#203A70', ralCode: 'RAL 5002', group: 'blue', nameUk: 'Ультрамариново-синій', nameRu: 'Ультрамариново-синий', nameEn: 'Ultramarine blue' },
  { hex: '#1D2B53', ralCode: 'RAL 5003', group: 'blue', nameUk: 'Сапфірово-синій', nameRu: 'Сапфирово-синий', nameEn: 'Sapphire blue' },
  { hex: '#1B2129', ralCode: 'RAL 5004', group: 'blue', nameUk: 'Чорно-синій', nameRu: 'Черно-синий', nameEn: 'Black blue' },
  { hex: '#00438A', ralCode: 'RAL 5005', group: 'blue', nameUk: 'Сигнальний синій', nameRu: 'Сигнальный синий', nameEn: 'Signal blue' },
  { hex: '#3B5A98', ralCode: 'RAL 5007', group: 'blue', nameUk: 'Діамантово-синій', nameRu: 'Бриллиантово-синий', nameEn: 'Brilliant blue' },
  { hex: '#26374A', ralCode: 'RAL 5008', group: 'blue', nameUk: 'Сіро-синій', nameRu: 'Серо-синий', nameEn: 'Grey blue' },
  { hex: '#2B5B84', ralCode: 'RAL 5009', group: 'blue', nameUk: 'Лазурно-синій', nameRu: 'Лазурно-синий', nameEn: 'Azure blue' },
  { hex: '#0E518D', ralCode: 'RAL 5010', group: 'blue', nameUk: 'Тирлич-синій', nameRu: 'Горечавково-синий', nameEn: 'Gentian blue' },
  { hex: '#232C3F', ralCode: 'RAL 5011', group: 'blue', nameUk: 'Сталевий синій', nameRu: 'Стальной синий', nameEn: 'Steel blue' },
  { hex: '#3B83B8', ralCode: 'RAL 5012', group: 'blue', nameUk: 'Світло-синій', nameRu: 'Светло-синий', nameEn: 'Light blue' },
  { hex: '#1E2740', ralCode: 'RAL 5013', group: 'blue', nameUk: 'Кобальтово-синій', nameRu: 'Кобальтово-синий', nameEn: 'Cobalt blue' },
  { hex: '#637D96', ralCode: 'RAL 5014', group: 'blue', nameUk: 'Голубино-синій', nameRu: 'Голубино-синий', nameEn: 'Pigeon blue' },
  { hex: '#007CB0', ralCode: 'RAL 5015', group: 'blue', nameUk: 'Небесно-синій', nameRu: 'Небесно-синий', nameEn: 'Sky blue' },
  { hex: '#063971', ralCode: 'RAL 5017', group: 'blue', nameUk: 'Трафіковий синій', nameRu: 'Трафиковый синий', nameEn: 'Traffic blue' },
  { hex: '#128695', ralCode: 'RAL 5018', group: 'blue', nameUk: 'Бірюзово-синій', nameRu: 'Бирюзово-синий', nameEn: 'Turquoise blue' },
  { hex: '#1B5583', ralCode: 'RAL 5019', group: 'blue', nameUk: 'Капрі синій', nameRu: 'Капри синий', nameEn: 'Capri blue' },
  { hex: '#1D334A', ralCode: 'RAL 5020', group: 'blue', nameUk: 'Океансько-синій', nameRu: 'Океанско-синий', nameEn: 'Ocean blue' },
  { hex: '#256D7B', ralCode: 'RAL 5021', group: 'blue', nameUk: 'Водяно-синій', nameRu: 'Водяно-синий', nameEn: 'Water blue' },

  // 6000 - Зелені
  { hex: '#327662', ralCode: 'RAL 6000', group: 'green', nameUk: 'Патиново-зелений', nameRu: 'Патиново-зеленый', nameEn: 'Patina green' },
  { hex: '#287448', ralCode: 'RAL 6001', group: 'green', nameUk: 'Смарагдово-зелений', nameRu: 'Изумрудно-зеленый', nameEn: 'Emerald green' },
  { hex: '#2D6B37', ralCode: 'RAL 6002', group: 'green', nameUk: 'Листяно-зелений', nameRu: 'Лиственно-зеленый', nameEn: 'Leaf green' },
  { hex: '#4B573E', ralCode: 'RAL 6003', group: 'green', nameUk: 'Оливково-зелений', nameRu: 'Оливково-зеленый', nameEn: 'Olive green' },
  { hex: '#1C4345', ralCode: 'RAL 6004', group: 'green', nameUk: 'Синьо-зелений', nameRu: 'Сине-зеленый', nameEn: 'Blue green' },
  { hex: '#0E4438', ralCode: 'RAL 6005', group: 'green', nameUk: 'Зелений мох', nameRu: 'Зеленый мох', nameEn: 'Moss green' },
  { hex: '#3B413A', ralCode: 'RAL 6006', group: 'green', nameUk: 'Сіро-оливковий', nameRu: 'Серо-оливковый', nameEn: 'Grey olive' },
  { hex: '#26392F', ralCode: 'RAL 6007', group: 'green', nameUk: 'Пляшково-зелений', nameRu: 'Бутылочно-зеленый', nameEn: 'Bottle green' },
  { hex: '#2D352E', ralCode: 'RAL 6008', group: 'green', nameUk: 'Коричнево-зелений', nameRu: 'Коричнево-зеленый', nameEn: 'Brown green' },
  { hex: '#213A2B', ralCode: 'RAL 6009', group: 'green', nameUk: 'Ялиново-зелений', nameRu: 'Елово-зеленый', nameEn: 'Fir green' },
  { hex: '#35682D', ralCode: 'RAL 6010', group: 'green', nameUk: 'Трав\'яно-зелений', nameRu: 'Травяно-зеленый', nameEn: 'Grass green' },
  { hex: '#6C7C59', ralCode: 'RAL 6011', group: 'green', nameUk: 'Резеда зелений', nameRu: 'Резеда зеленый', nameEn: 'Reseda green' },
  { hex: '#283430', ralCode: 'RAL 6012', group: 'green', nameUk: 'Чорно-зелений', nameRu: 'Черно-зеленый', nameEn: 'Black green' },
  { hex: '#6C7156', ralCode: 'RAL 6013', group: 'green', nameUk: 'Очеретяно-зелений', nameRu: 'Тростниково-зеленый', nameEn: 'Reed green' },
  { hex: '#057D54', ralCode: 'RAL 6016', group: 'green', nameUk: 'Бірюзово-зелений', nameRu: 'Бирюзово-зеленый', nameEn: 'Turquoise green' },
  { hex: '#4C9141', ralCode: 'RAL 6017', group: 'green', nameUk: 'Травнево-зелений', nameRu: 'Майско-зеленый', nameEn: 'May green' },
  { hex: '#57A639', ralCode: 'RAL 6018', group: 'green', nameUk: 'Жовто-зелений / Лайм', nameRu: 'Желто-зеленый / Лайм', nameEn: 'Yellow green' },
  { hex: '#B9D9EB', ralCode: 'RAL 6019', group: 'green', nameUk: 'Пастельно-зелений', nameRu: 'Пастельно-зеленый', nameEn: 'Pastel green' },
  { hex: '#2E3B32', ralCode: 'RAL 6020', group: 'green', nameUk: 'Хромово-зелений', nameRu: 'Хромово-зеленый', nameEn: 'Chrome green' },
  { hex: '#87A96B', ralCode: 'RAL 6021', group: 'green', nameUk: 'Блідо-зелений', nameRu: 'Бледно-зеленый', nameEn: 'Pale green' },
  { hex: '#308446', ralCode: 'RAL 6024', group: 'green', nameUk: 'Трафіковий зелений', nameRu: 'Трафиковый зеленый', nameEn: 'Traffic green' },
  { hex: '#3B7A57', ralCode: 'RAL 6025', group: 'green', nameUk: 'Папоротево-зелений', nameRu: 'Папоротниково-зеленый', nameEn: 'Fern green' },
  { hex: '#005F56', ralCode: 'RAL 6026', group: 'green', nameUk: 'Опалово-зелений', nameRu: 'Опалово-зеленый', nameEn: 'Opal green' },
  { hex: '#84C3BE', ralCode: 'RAL 6027', group: 'green', nameUk: 'Світло-зелений', nameRu: 'Светло-зеленый', nameEn: 'Light green' },
  { hex: '#2D5744', ralCode: 'RAL 6028', group: 'green', nameUk: 'Сосново-зелений', nameRu: 'Сосново-зеленый', nameEn: 'Pine green' },
  { hex: '#007A5E', ralCode: 'RAL 6029', group: 'green', nameUk: 'М\'ятно-зелений', nameRu: 'Мятно-зеленый', nameEn: 'Mint green' },
  { hex: '#00A550', ralCode: 'RAL 6037', group: 'green', nameUk: 'Чистий зелений', nameRu: 'Чистый зеленый', nameEn: 'Pure green' },

  // 7000 - Сірі
  { hex: '#78858B', ralCode: 'RAL 7000', group: 'grey', nameUk: 'Білячо-сірий', nameRu: 'Беличье-серый', nameEn: 'Squirrel grey' },
  { hex: '#8A959E', ralCode: 'RAL 7001', group: 'grey', nameUk: 'Сріблясто-сірий', nameRu: 'Серебристо-серый', nameEn: 'Silver grey' },
  { hex: '#7A7B6D', ralCode: 'RAL 7002', group: 'grey', nameUk: 'Оливково-сірий', nameRu: 'Оливково-серый', nameEn: 'Olive grey' },
  { hex: '#6C7059', ralCode: 'RAL 7003', group: 'grey', nameUk: 'Мохово-сірий', nameRu: 'Мохово-серый', nameEn: 'Moss grey' },
  { hex: '#969992', ralCode: 'RAL 7004', group: 'grey', nameUk: 'Сигнальний сірий', nameRu: 'Сигнальный серый', nameEn: 'Signal grey' },
  { hex: '#6C706B', ralCode: 'RAL 7005', group: 'grey', nameUk: 'Мишачо-сірий', nameRu: 'Мышино-серый', nameEn: 'Mouse grey' },
  { hex: '#756F61', ralCode: 'RAL 7006', group: 'grey', nameUk: 'Бежево-сірий', nameRu: 'Бежево-серый', nameEn: 'Beige grey' },
  { hex: '#746643', ralCode: 'RAL 7008', group: 'grey', nameUk: 'Хакі сірий', nameRu: 'Хаки серый', nameEn: 'Khaki grey' },
  { hex: '#5B6259', ralCode: 'RAL 7009', group: 'grey', nameUk: 'Зелено-сірий', nameRu: 'Зелено-серый', nameEn: 'Green grey' },
  { hex: '#575D57', ralCode: 'RAL 7010', group: 'grey', nameUk: 'Брезентово-сірий', nameRu: 'Брезентово-серый', nameEn: 'Tarpaulin grey' },
  { hex: '#555D61', ralCode: 'RAL 7011', group: 'grey', nameUk: 'Залізно-сірий', nameRu: 'Железно-серый', nameEn: 'Iron grey' },
  { hex: '#59626A', ralCode: 'RAL 7012', group: 'grey', nameUk: 'Базальтово-сірий', nameRu: 'Базальтово-серый', nameEn: 'Basalt grey' },
  { hex: '#51564C', ralCode: 'RAL 7013', group: 'grey', nameUk: 'Коричнево-сірий', nameRu: 'Коричнево-серый', nameEn: 'Brown grey' },
  { hex: '#4C5055', ralCode: 'RAL 7015', group: 'grey', nameUk: 'Сланцево-сірий', nameRu: 'Сланцево-серый', nameEn: 'Slate grey' },
  { hex: '#373D43', ralCode: 'RAL 7016', group: 'grey', nameUk: 'Антрацитово-сірий / Графіт', nameRu: 'Антрацитовый серый / Графит', nameEn: 'Anthracite grey' },
  { hex: '#2F353B', ralCode: 'RAL 7021', group: 'grey', nameUk: 'Чорно-сірий', nameRu: 'Черно-серый', nameEn: 'Black grey' },
  { hex: '#4B4D4B', ralCode: 'RAL 7022', group: 'grey', nameUk: 'Умбра сірий', nameRu: 'Умбра серый', nameEn: 'Umbra grey' },
  { hex: '#818479', ralCode: 'RAL 7023', group: 'grey', nameUk: 'Бетонно-сірий', nameRu: 'Бетонно-серый', nameEn: 'Concrete grey' },
  { hex: '#474A51', ralCode: 'RAL 7024', group: 'grey', nameUk: 'Графітово-сірий', nameRu: 'Графитово-серый', nameEn: 'Graphite grey' },
  { hex: '#363D43', ralCode: 'RAL 7026', group: 'grey', nameUk: 'Гранітно-сірий', nameRu: 'Гранитно-серый', nameEn: 'Granite grey' },
  { hex: '#929288', ralCode: 'RAL 7030', group: 'grey', nameUk: 'Кам\'яно-сірий', nameRu: 'Каменно-серый', nameEn: 'Stone grey' },
  { hex: '#5B686D', ralCode: 'RAL 7031', group: 'grey', nameUk: 'Синьо-сірий', nameRu: 'Сине-серый', nameEn: 'Blue grey' },
  { hex: '#B8B7A9', ralCode: 'RAL 7032', group: 'grey', nameUk: 'Гальково-сірий', nameRu: 'Галечно-серый', nameEn: 'Pebble grey' },
  { hex: '#7D847D', ralCode: 'RAL 7033', group: 'grey', nameUk: 'Цементно-сірий', nameRu: 'Цементно-серый', nameEn: 'Cement grey' },
  { hex: '#8F8B74', ralCode: 'RAL 7034', group: 'grey', nameUk: 'Жовто-сірий', nameRu: 'Желто-серый', nameEn: 'Yellow grey' },
  { hex: '#CBD0CC', ralCode: 'RAL 7035', group: 'grey', nameUk: 'Світло-сірий', nameRu: 'Светло-серый', nameEn: 'Light grey' },
  { hex: '#9A9B9B', ralCode: 'RAL 7036', group: 'grey', nameUk: 'Платиново-сірий', nameRu: 'Платиново-серый', nameEn: 'Platinum grey' },
  { hex: '#7C7D7D', ralCode: 'RAL 7037', group: 'grey', nameUk: 'Пильно-сірий', nameRu: 'Пыльно-серый', nameEn: 'Dusty grey' },
  { hex: '#B5B8B1', ralCode: 'RAL 7038', group: 'grey', nameUk: 'Агатово-сірий', nameRu: 'Агатово-серый', nameEn: 'Agate grey' },
  { hex: '#6C6E6B', ralCode: 'RAL 7039', group: 'grey', nameUk: 'Кварцово-сірий', nameRu: 'Кварцево-серый', nameEn: 'Quartz grey' },
  { hex: '#9DA3A6', ralCode: 'RAL 7040', group: 'grey', nameUk: 'Віконно-сірий', nameRu: 'Оконно-серый', nameEn: 'Window grey' },
  { hex: '#8D948D', ralCode: 'RAL 7042', group: 'grey', nameUk: 'Трафіковий сірий A', nameRu: 'Трафиковый серый A', nameEn: 'Traffic grey A' },
  { hex: '#4E5452', ralCode: 'RAL 7043', group: 'grey', nameUk: 'Трафіковий сірий B', nameRu: 'Трафиковый серый B', nameEn: 'Traffic grey B' },
  { hex: '#BDBDBA', ralCode: 'RAL 7044', group: 'grey', nameUk: 'Шовково-сірий', nameRu: 'Шелково-серый', nameEn: 'Silk grey' },

  // 8000 - Коричневі
  { hex: '#594933', ralCode: 'RAL 8000', group: 'brown', nameUk: 'Зелено-коричневий', nameRu: 'Зелено-коричневый', nameEn: 'Green brown' },
  { hex: '#9C6B30', ralCode: 'RAL 8001', group: 'brown', nameUk: 'Охра коричнева', nameRu: 'Охра коричневая', nameEn: 'Ochre brown' },
  { hex: '#734222', ralCode: 'RAL 8002', group: 'brown', nameUk: 'Сигнальний коричневий', nameRu: 'Сигнальный коричневый', nameEn: 'Signal brown' },
  { hex: '#8D4925', ralCode: 'RAL 8003', group: 'brown', nameUk: 'Глиняно-коричневий', nameRu: 'Глиняно-коричневый', nameEn: 'Clay brown' },
  { hex: '#8F3F2A', ralCode: 'RAL 8004', group: 'brown', nameUk: 'Мідно-коричневий', nameRu: 'Медно-коричневый', nameEn: 'Copper brown' },
  { hex: '#6F4A2F', ralCode: 'RAL 8007', group: 'brown', nameUk: 'Оленячий коричневий', nameRu: 'Олений коричневый', nameEn: 'Fawn brown' },
  { hex: '#705335', ralCode: 'RAL 8008', group: 'brown', nameUk: 'Оливково-коричневий', nameRu: 'Оливково-коричневый', nameEn: 'Olive brown' },
  { hex: '#5A3D28', ralCode: 'RAL 8011', group: 'brown', nameUk: 'Горіхово-коричневий', nameRu: 'Орехово-коричневый', nameEn: 'Nut brown' },
  { hex: '#673831', ralCode: 'RAL 8012', group: 'brown', nameUk: 'Червоно-коричневий', nameRu: 'Красно-коричневый', nameEn: 'Red brown' },
  { hex: '#49322B', ralCode: 'RAL 8014', group: 'brown', nameUk: 'Сепія коричневий', nameRu: 'Сепия коричневый', nameEn: 'Sepia brown' },
  { hex: '#633A34', ralCode: 'RAL 8015', group: 'brown', nameUk: 'Каштаново-коричневий', nameRu: 'Каштаново-коричневый', nameEn: 'Chestnut brown' },
  { hex: '#4C2F27', ralCode: 'RAL 8016', group: 'brown', nameUk: 'Махагоново-коричневий', nameRu: 'Махагоново-коричневый', nameEn: 'Mahogany brown' },
  { hex: '#442F29', ralCode: 'RAL 8017', group: 'brown', nameUk: 'Шоколадно-коричневий', nameRu: 'Шоколадно-коричневый', nameEn: 'Chocolate brown' },
  { hex: '#3D3635', ralCode: 'RAL 8019', group: 'brown', nameUk: 'Сіро-коричневий', nameRu: 'Серо-коричневый', nameEn: 'Grey brown' },
  { hex: '#2B2625', ralCode: 'RAL 8022', group: 'brown', nameUk: 'Чорно-коричневий', nameRu: 'Черно-коричневый', nameEn: 'Black brown' },
  { hex: '#A65E2E', ralCode: 'RAL 8023', group: 'brown', nameUk: 'Оранжево-коричневий', nameRu: 'Оранжево-коричневый', nameEn: 'Orange brown' },
  { hex: '#79503F', ralCode: 'RAL 8024', group: 'brown', nameUk: 'Майроново-коричневий', nameRu: 'Майроново-коричневый', nameEn: 'Mayron brown' },

  // 9000 - Чорні та Білі
  { hex: '#FDF4E3', ralCode: 'RAL 9001', group: 'black_white', nameUk: 'Кремовий', nameRu: 'Кремовый', nameEn: 'Cream' },
  { hex: '#D7D5CB', ralCode: 'RAL 9002', group: 'black_white', nameUk: 'Сіро-білий', nameRu: 'Серо-белый', nameEn: 'Grey white' },
  { hex: '#F4F4F4', ralCode: 'RAL 9003', group: 'black_white', nameUk: 'Сигнальний білий', nameRu: 'Сигнальный белый', nameEn: 'Signal white' },
  { hex: '#282828', ralCode: 'RAL 9004', group: 'black_white', nameUk: 'Сигнальний чорний', nameRu: 'Сигнальный черный', nameEn: 'Signal black' },
  { hex: '#0A0A0A', ralCode: 'RAL 9005', group: 'black_white', nameUk: 'Глибоко-чорний', nameRu: 'Глубокий черный', nameEn: 'Jet black' },
  { hex: '#A5A8A6', ralCode: 'RAL 9006', group: 'black_white', nameUk: 'Білий алюміній', nameRu: 'Белый алюминий', nameEn: 'White aluminium' },
  { hex: '#8F9695', ralCode: 'RAL 9007', group: 'black_white', nameUk: 'Сірий алюміній', nameRu: 'Серый алюминий', nameEn: 'Grey aluminium' },
  { hex: '#F7F7F7', ralCode: 'RAL 9010', group: 'black_white', nameUk: 'Чистий білий', nameRu: 'Чистый белый', nameEn: 'Pure white' },
  { hex: '#1E1E1E', ralCode: 'RAL 9011', group: 'black_white', nameUk: 'Графітово-чорний', nameRu: 'Графитово-черный', nameEn: 'Graphite black' },
  { hex: '#F6F6F6', ralCode: 'RAL 9016', group: 'black_white', nameUk: 'Білосніжний (Трафіковий)', nameRu: 'Белоснежный (Трафиковый)', nameEn: 'Traffic white' },
  { hex: '#1D1E1E', ralCode: 'RAL 9017', group: 'black_white', nameUk: 'Трафіковий чорний', nameRu: 'Трафиковый черный', nameEn: 'Traffic black' },
  { hex: '#D7D7D7', ralCode: 'RAL 9018', group: 'black_white', nameUk: 'Папірус білий', nameRu: 'Папирус белый', nameEn: 'Papyrus white' },
];
